name: size
on:
  # this action will error unless run in a pr context
  pull_request_target:
    branches:
      - main

env:
  BUNDLE_SIZE: true

permissions: {}

jobs:
  # Build current and upload stats.json
  # You may replace this with your own build method. All that
  # is required is that the stats.json be an artifact
  build-head:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: corepack enable
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: lts/*

      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: ğŸ›  Build project
        run: pnpm build

      - name: â« Upload stats.json
        uses: actions/upload-artifact@v4
        with:
          name: head-stats
          path: ./packages/*/stats.json

  # Build base for comparison and upload stats.json
  # You may replace this with your own build method. All that
  # is required is that the stats.json be an artifact
  build-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ github.base_ref }}
      - run: corepack enable
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: lts/*

      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: ğŸ›  Build project
        run: pnpm build

      - name: â« Upload stats.json
        uses: actions/upload-artifact@v4
        with:
          name: base-stats
          path: ./packages/*/stats.json

  # run the action against the stats.json files
  compare:
    runs-on: ubuntu-latest
    needs: [build-base, build-head]
    permissions:
      pull-requests: write
      issues: write
    strategy:
      matrix:
        package: [nuxi, nuxt-cli, create-nuxt]
    steps:
      - name: â¬ Download stats.json
        uses: actions/download-artifact@v5
      - uses: twk3/rollup-size-compare-action@v1.2.0
        with:
          title: ${{ matrix.package }} size comparison
          github-token: ${{ secrets.GITHUB_TOKEN }}
          current-stats-json-path: ./head-stats/${{ matrix.package }}/stats.json
          base-stats-json-path: ./base-stats/${{ matrix.package }}/stats.json
