name: size

on:
  pull_request:
    branches:
      - main

env:
  BUNDLE_SIZE: true

permissions: {}

jobs:
  # Build current and upload stats.json
  # You may replace this with your own build method. All that
  # is required is that the stats.json be an artifact
  build-head:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - run: corepack enable
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: lts/*

      - name: ğŸ“¦ Install dependencies
        run: pnpm install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ›  Build project
        run: pnpm build

      - name: ğŸ’¾ Save PR number
        run: echo "${{ github.event.pull_request.number }}" > pr-number.txt

      - name: â« Upload stats.json
        uses: actions/upload-artifact@v5
        with:
          name: head-stats
          path: ./packages/*/stats.json

      - name: â« Upload PR number
        uses: actions/upload-artifact@v5
        with:
          name: pr-number
          path: pr-number.txt

  # Build base for comparison and upload stats.json
  # You may replace this with your own build method. All that
  # is required is that the stats.json be an artifact
  build-base:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          ref: ${{ github.base_ref }}
      - run: corepack enable
      - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version: lts/*

      - name: ğŸ“¦ Install dependencies
        run:
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ›  Build project
        run: pnpm build

      - name: â« Upload stats.json
        uses: actions/upload-artifact@v5
        with:
          name: base-stats
          path: ./packages/*/stats.json
