name: size-build
on:
  pull_request:
    branches:
      - main

env:
  BUNDLE_SIZE: true

permissions:
  contents: read

jobs:
  # Build current and upload stats.json
  build-head:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
      - run: corepack enable
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: lts/*

      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: ğŸ›  Build project
        run: pnpm build

      - name: â« Upload stats.json
        uses: actions/upload-artifact@v4
        with:
          name: head-stats
          path: ./packages/*/stats.json

  # Build base for comparison and upload stats.json
  build-base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ github.base_ref }}
      - run: corepack enable
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: lts/*

      - name: ğŸ“¦ Install dependencies
        run: pnpm install

      - name: ğŸ›  Build project
        run: pnpm build

      - name: â« Upload stats.json
        uses: actions/upload-artifact@v4
        with:
          name: base-stats
          path: ./packages/*/stats.json
